# Generated by Django 6.0.8 on 2026-09-08 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='d1_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='d3_enabled',
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='notify_time',
            field=models.TimeField(db_default=datetime.time(8, 0), default=datetime.time(8, 0)),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='timezone',
            field=models.CharField(db_default='Asia/Seoul', default='Asia/Seoul', max_length=50),
        ),
    ]
