# Generated by Django 6.0.8 on 2026-09-08 06:58

import config.db_fields
import datetime
import django.db.models.deletion
import foods.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.CharField(default=foods.models._default_food_id, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', config.db_fields.MySQLEnumField(choices=[('유제품', '유제품'), ('채소', '채소'), ('과일', '과일'), ('육류', '육류'), ('기타', '기타')], max_length=10)),
                ('quantity', config.db_fields.UnsignedIntField(default=1)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField()),
                ('storage_location', config.db_fields.MySQLEnumField(choices=[('냉장', '냉장'), ('냉동', '냉동'), ('실온', '실온')], default='냉장', max_length=4)),
                ('memo', models.CharField(blank=True, max_length=200, null=True)),
                ('status', config.db_fields.MySQLEnumField(choices=[('보관중', '보관중'), ('구조', '구조'), ('폐기', '폐기')], default='보관중', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'foods',
                'indexes': [models.Index(fields=['user', 'status', 'expiry_date'], name='idx_foods_user_status_expiry')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='chk_foods_quantity')],
            },
        ),
    ]
