# Generated by Django 6.0.8 on 2026-09-08 06:59

import config.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=config.db_fields.UnsignedIntField(db_default=1, default=1),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=config.db_fields.MySQLEnumField(choices=[('보관중', '보관중'), ('구조', '구조'), ('폐기', '폐기')], db_default='보관중', default='보관중', max_length=4),
        ),
        migrations.AlterField(
            model_name='food',
            name='storage_location',
            field=config.db_fields.MySQLEnumField(choices=[('냉장', '냉장'), ('냉동', '냉동'), ('실온', '실온')], db_default='냉장', default='냉장', max_length=4),
        ),
    ]
