# Generated by Django 6.0.8 on 2026-09-08 06:58

import config.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageTip',
            fields=[
                ('tip_id', config.db_fields.UnsignedAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'storage_tips',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', config.db_fields.UnsignedAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
                ('sort_order', config.db_fields.UnsignedIntField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faqs',
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['sort_order'], name='idx_faqs_sort')],
            },
        ),
    ]
