# Generated by Django 6.0.8 on 2026-09-08 06:58

import config.db_fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodActivityLog',
            fields=[
                ('log_id', config.db_fields.UnsignedBigAutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('category', config.db_fields.MySQLEnumField(choices=[('유제품', '유제품'), ('채소', '채소'), ('과일', '과일'), ('육류', '육류'), ('기타', '기타')], max_length=10)),
                ('action', config.db_fields.MySQLEnumField(choices=[('구조', '구조'), ('폐기', '폐기')], max_length=4)),
                ('acted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(blank=True, db_column='food_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='foods.food')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'food_activity_logs',
                'indexes': [models.Index(fields=['user', 'acted_at'], name='idx_logs_user_acted'), models.Index(fields=['user', 'action', 'acted_at'], name='idx_logs_user_action_acted')],
            },
        ),
    ]
